scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance: 'container'
          service: 'prometheus'

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]